import { GiftAsset, Currency } from '@/types';

export const giftMetadata: GiftAsset[] = [
   {
      name: '100 Percent',
      amount: 100,
      unit: Currency.SAT,
      description: '100% symbol',
      selectedSrc: '/eGifts/selected/100percent_100.png',
      unselectedSrc: '/eGifts/unselected/100percent_100.png',
      creatorPubkey: null,
   },
   {
      name: 'Burger',
      amount: 5000,
      unit: Currency.SAT,
      description: 'A delicious burger',
      selectedSrc: '/eGifts/selected/burger_5000.png',
      unselectedSrc: '/eGifts/unselected/burger_5000.png',
      creatorPubkey: null,
   },
   {
      name: 'Candy',
      amount: 100,
      unit: Currency.SAT,
      description: 'A sweet candy',
      selectedSrc: '/eGifts/selected/candy_100.png',
      unselectedSrc: '/eGifts/unselected/candy_100.png',
      creatorPubkey: null,
   },
   {
      name: 'Champagne',
      amount: 10000,
      unit: Currency.SAT,
      description: 'A bottle of champagne',
      selectedSrc: '/eGifts/selected/champagne_10000.png',
      unselectedSrc: '/eGifts/unselected/champagne_10000.png',
      creatorPubkey: null,
   },
   {
      name: 'Cheese',
      amount: 500,
      unit: Currency.SAT,
      description: 'A piece of cheese',
      selectedSrc: '/eGifts/selected/cheese_500.png',
      unselectedSrc: '/eGifts/unselected/cheese_500.png',
      creatorPubkey: null,
   },
   {
      name: 'Chocolate',
      amount: 100,
      unit: Currency.SAT,
      description: 'A chocolate bar',
      selectedSrc: '/eGifts/selected/chocolate_100.png',
      unselectedSrc: '/eGifts/unselected/chocolate_100.png',
      creatorPubkey: null,
   },
   {
      name: 'Dolphin',
      amount: 5000,
      unit: Currency.SAT,
      description: 'A playful dolphin',
      selectedSrc: '/eGifts/selected/dolphin_5000.png',
      unselectedSrc: '/eGifts/unselected/dolphin_5000.png',
      creatorPubkey: null,
   },
   {
      name: 'Ferris Wheel',
      amount: 10000,
      unit: Currency.SAT,
      description: 'A colorful ferris wheel',
      selectedSrc: '/eGifts/selected/ferriswheel_10000.png',
      unselectedSrc: '/eGifts/unselected/ferriswheel_10000.png',
      creatorPubkey: null,
   },
   {
      name: 'Full Moon',
      amount: 500,
      unit: Currency.SAT,
      description: 'A bright full moon',
      selectedSrc: '/eGifts/selected/fullmoon_500.png',
      unselectedSrc: '/eGifts/unselected/fullmoon_500.png',
      creatorPubkey: null,
   },
   {
      name: 'Headless Bitcoin',
      amount: 21000,
      unit: Currency.SAT,
      description: 'A headless Bitcoin symbol',
      selectedSrc: '/eGifts/selected/headlessbitcoin_21000.png',
      unselectedSrc: '/eGifts/unselected/headlessbitcoin_21000.png',
      creatorPubkey: null,
   },
   {
      name: 'Kitty',
      amount: 5000,
      unit: Currency.SAT,
      description: 'A cute kitty',
      selectedSrc: '/eGifts/selected/kitty_5000.png',
      unselectedSrc: '/eGifts/unselected/kitty_5000.png',
      creatorPubkey: null,
   },
   {
      name: 'Monopoly Bitcoin',
      amount: 21000,
      unit: Currency.SAT,
      description: 'A Bitcoin-themed Monopoly symbol',
      selectedSrc: '/eGifts/selected/monopolybitcoin_21000.png',
      unselectedSrc: '/eGifts/unselected/monopolybitcoin_21000.png',
      creatorPubkey: null,
   },
   {
      name: 'Party Popper',
      amount: 1000,
      unit: Currency.SAT,
      description: 'A festive party popper',
      selectedSrc: '/eGifts/selected/partypopper_1000.png',
      unselectedSrc: '/eGifts/unselected/partypopper2_1000.png',
      creatorPubkey: null,
   },
   {
      name: 'Pill',
      amount: 1000,
      unit: Currency.SAT,
      description: 'A medicinal pill',
      selectedSrc: '/eGifts/selected/pill_1000.png',
      unselectedSrc: '/eGifts/unselected/pill_1000.png',
      creatorPubkey: null,
   },
   {
      name: 'Rocket Ship',
      amount: 10000,
      unit: Currency.SAT,
      description: 'A soaring rocket ship',
      selectedSrc: '/eGifts/selected/rocketship_10000.png',
      unselectedSrc: '/eGifts/unselected/rocketship_10000.png',
      creatorPubkey: null,
   },
   {
      name: 'Satoshi Bitcoin',
      amount: 21000,
      unit: Currency.SAT,
      description: 'A Satoshi-themed Bitcoin symbol',
      selectedSrc: '/eGifts/selected/satoshibitcoin_21000.png',
      unselectedSrc: '/eGifts/unselected/satoshibitcoin_21000.png',
      creatorPubkey: null,
   },
   {
      name: 'Sun',
      amount: 500,
      unit: Currency.SAT,
      description: 'A bright shining sun',
      selectedSrc: '/eGifts/selected/sun_500.png',
      unselectedSrc: '/eGifts/unselected/sun_500.png',
      creatorPubkey: null,
   },
   {
      name: 'Tombstone',
      amount: 1000,
      unit: Currency.SAT,
      description: 'A spooky tombstone',
      selectedSrc: '/eGifts/selected/tombstone_1000.png',
      unselectedSrc: '/eGifts/unselected/tombstone_1000.png',
      creatorPubkey: null,
   },
   {
      name: 'Unicorn Bitcoin',
      amount: 21000,
      unit: Currency.SAT,
      description: 'A magical unicorn-themed Bitcoin',
      selectedSrc: '/eGifts/selected/unicornbitcoin_21000.png',
      unselectedSrc: '/eGifts/unselected/unicornbitcoin_21000.png',
      creatorPubkey: null,
   },
   {
      name: 'Vampire',
      amount: 5000,
      unit: Currency.SAT,
      description: 'A spooky vampire',
      selectedSrc: '/eGifts/selected/vampire_5000.png',
      unselectedSrc: '/eGifts/unselected/vampire_5000.png',
      creatorPubkey: null,
   },
   {
      name: 'Witch',
      amount: 10000,
      unit: Currency.SAT,
      description: 'A magical witch',
      selectedSrc: '/eGifts/selected/witch_10000.png',
      unselectedSrc: '/eGifts/unselected/witch_10000.png',
      creatorPubkey: null,
   },
];
