import './instrument.server';
import { PassThrough } from 'node:stream';

import { createReadableStreamFromReadable } from '@react-router/node';
import * as Sentry from '@sentry/react-router';
import {
  getMetaTagTransformer,
  wrapSentryHandleRequest,
} from '@sentry/react-router';
import { isbot } from 'isbot';
import type { RenderToPipeableStreamOptions } from 'react-dom/server';
import { renderToPipeableStream } from 'react-dom/server';
import type {
  EntryContext,
  unstable_RouterContextProvider,
} from 'react-router';
import { ServerRouter } from 'react-router';

export const streamTimeout = 5_000;

function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  routerContext: EntryContext,
  // If middlware is not enabled the type should be AppLoadContext
  // biome-ignore lint/correctness/noUnusedVariables: file generated by react router by running `bunx react-router reveal`
  loadContext: unstable_RouterContextProvider,
) {
  return new Promise((resolve, reject) => {
    let shellRendered = false;
    const userAgent = request.headers.get('user-agent');

    // Ensure requests from bots and SPA Mode renders wait for all content to load before responding
    // https://react.dev/reference/react-dom/server/renderToPipeableStream#waiting-for-all-content-to-load-for-crawlers-and-static-generation
    const readyOption: keyof RenderToPipeableStreamOptions =
      (userAgent && isbot(userAgent)) || routerContext.isSpaMode
        ? 'onAllReady'
        : 'onShellReady';

    const { pipe, abort } = renderToPipeableStream(
      <ServerRouter context={routerContext} url={request.url} />,
      {
        [readyOption]() {
          shellRendered = true;
          const body = new PassThrough();
          const stream = createReadableStreamFromReadable(body);

          responseHeaders.set('Content-Type', 'text/html');

          resolve(
            new Response(stream, {
              headers: responseHeaders,
              status: responseStatusCode,
            }),
          );

          pipe(getMetaTagTransformer(body));
        },
        onShellError(error: unknown) {
          reject(error);
        },
        onError(error: unknown) {
          // biome-ignore lint/style/noParameterAssign: file generated by react router by running `bunx react-router reveal`
          responseStatusCode = 500;
          // Log streaming rendering errors from inside the shell.  Don't log
          // errors encountered during initial shell rendering since they'll
          // reject and get logged in handleDocumentRequest.
          if (shellRendered) {
            console.error(error);
          }
        },
      },
    );

    // Abort the rendering stream after the `streamTimeout` so it has time to
    // flush down the rejected boundaries
    setTimeout(abort, streamTimeout + 1000);
  });
}

// wrapSentryHandleRequest doesn't take into account the possibility of middlware being enabled so has loadContext type defined as AppLoadContext.
// However it only passes the loadContext to handleRequest so doesn't really matter. We can just ignore the type error.
// See the source code for wrapSentryHandleRequest here: https://github.com/getsentry/sentry-javascript/blob/10.5.0/packages/react-router/src/server/wrapSentryHandleRequest.ts
// biome-ignore lint/suspicious/noExplicitAny: see comment above
export default wrapSentryHandleRequest(handleRequest as any);

export const handleError = Sentry.createSentryHandleError({
  logErrors: true,
});
